/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Baguette(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/baguette.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions['Run'].play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <skinnedMesh
            name="_100Avatars_194_CoolCloud"
            geometry={nodes._100Avatars_194_CoolCloud.geometry}
            material={materials._194_CoolCloud}
            skeleton={nodes._100Avatars_194_CoolCloud.skeleton}
            morphTargetDictionary={
              nodes._100Avatars_194_CoolCloud.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes._100Avatars_194_CoolCloud.morphTargetInfluences
            }
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/baguette.glb");
