/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef } from "react"
import { useGLTF, useAnimations, Text, Billboard } from "@react-three/drei"
import { SkeletonUtils } from "three-stdlib"
import { useGraph } from "@react-three/fiber"
import * as THREE from "three"
export function Zombie({ zombie, ...props }) {
  const group = useRef()
  const { scene, materials, animations } = useGLTF("./models/zombie.glb")
  // 加上这两句
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone)

  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions['Run'].time=Math.random()*actions['Run'].getClip().duration
    actions["Run"].play()
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      {/* NAEM */}
      {/* 广告牌组件 */}
      <Billboard position-y={4}>
        <Text fontSize={0.42} font="./fonts/Poppins-Black.ttf">
          {zombie.name}
          <meshStandardMaterial color="red" side={THREE.DoubleSide} />
        </Text>
      </Billboard>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <skinnedMesh
            name="_100Avatars_109_AlienSkeleton"
            geometry={nodes._100Avatars_109_AlienSkeleton.geometry}
            material={materials._109_AlienSkeleton}
            skeleton={nodes._100Avatars_109_AlienSkeleton.skeleton}
            morphTargetDictionary={
              nodes._100Avatars_109_AlienSkeleton.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes._100Avatars_109_AlienSkeleton.morphTargetInfluences
            }
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("./models/zombie.glb")
